### PR TITLE
cobrajson: keep integers as integers when parsing json input

### PR DESCRIPTION
**Pull request by spikeliu**
#9

### CODE REVIEW

**Comment by jonls** [comment]
Thanks, this is great 👍  I didn't know about the `is_integer` method on `float`. How did you test that this works correctly?

**Comment by spikeliu** [comment]
I actually tried to use `decimal.Decimal()` first, but it won't work for all cases. Like, the stoichiometric value can be kept as normal integer, but the flux limit in `model.yaml` would become `!! float 1000.0`, which is a very weird expression. So I change it to just use `int()` or `float()` to transform them. In the official document, the `float()` is used as the `parse_float`. I use that e_coli_core model from bigg as a test case, after I import it, I went into the reaction.yaml to see if those integers are still integers.

**Comment by jonls** [comment]
Hmm... I guess that explains why I haven't been using `is_integer`. Were you able to track down why you saw that `!!float` expression in the YAML file?

**Comment by jonls** [comment]
With the last commit will this handle all the issues we discussed?

**Comment by spikeliu** [comment]
I think so. I haven't seen anything wrong with it.

**Pull request merged**
